package lexer;

/*

    Filename: JavaSymbol.java
    Version: 1
    ID: 1.1

 */

/*

    This file provides a mechanism to access the data of the lexer file generated by JFlex.

    @author Ali Shokri
    @author Manan Joshi

 */

public class JavaSymbol extends java_cup.runtime.Symbol {

    private int line;

    private int column;

    public JavaSymbol(int type, int line, int column) {
        this(type, line, column, -1, -1, null);
    }

    public JavaSymbol(int type, int line, int column, Object value) {
        this(type, line, column, -1, -1, value);
    }

    public JavaSymbol(int type, int line, int column, int left, int right, Object value) {
        super(type, left, right, value);
        this.line = line;
        this.column = column;
    }

    public int getLine() {
        return line;
    }

    public int getColumn() {
        return column;
    }

    /*
        This method returns the string value for all the eMiniJava symbols in a formatted manner which
        is then written to the output file.
     */

    public String toString() {

        if (CommonConstants.getSymbolName(sym) != CommonConstants.getSymbolName(1))
            return line + " : " + column + "\t" +
                    CommonConstants.getSymbolName(sym) + (value == null ? "()" : ("(" + value + ")"));
        return "";

    }

}